# SkyPro Lesson 18 part1
### Проблема с данными для самопроверки в "part2/password_check"

Cделал в файле ```./part2/password_check/main.py``` две проверки - одну с данными для самопроверки, вторую с данными из ```test_hard.py```. С данными для самопроверки выдаёт False.

